name = "enden-link"
main = "src/index.ts"
compatibility_date = "2025-06-17"

routes = [
  { pattern = "link.enden.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "ENDEN_LINK_URLS"
id = "fd2f7d1b50374ab096f46f9d4abdd20f"
preview_id = "fd2f7d1b50374ab096f46f9d4abdd20f"

[[analytics_engine_datasets]]
binding = "ENDEN_LINK_VIEWS"
dataset = "enden_link_views"
